### ISSUE TITLE
Improve https://hub.docker.com/r/library/mongo-express/

### ISSUE THREAD

**Issue by tmaier** [mongo-express/mongo-express-docker#3]
* [ ] Consider to set-up as automated build
* [ ] Add the `Dockerfile` to review at https://hub.docker.com/r/library/mongo-express/
* [ ] Link the github repo at docker hub

**Comment by knickers** [comment]
Thank you for your suggestions @tmaier.

The docker official images work differently than user images. They do not support automated builds because they run custom build scripts in order to build many versions of the same projects. Here is the build declaration for mongo-express: https://github.com/docker-library/official-images/blob/master/library/mongo-express. It basically just declares the version numbers and associated git hashes.

I didn't find any way to associate the dockerfile to the image when I researched how to submit the original pr for the official image, but there is a link to it next to the supported version numbers on the repository page.

The descriptions are also built through a script so that the supported versions will automatically update. I'll work on updating this.
