### ISSUE TITLE
Yarn error while building image in Node 18 and 20

### ISSUE THREAD

**Issue by LaurentGoderre** [mongo-express/mongo-express-docker#97]
Error is

```
error Couldn't find any versions for "mongodb-query-parser" that matches "patch:mongodb-query-parser@npm%3A2.4.6#~/.yarn/patches/mongodb-query-parser-npm-2.4.6-234abad2fc.patch"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by LaurentGoderre** [comment]
This will obly apply to 1.01. 1.0.0 seems to work fine

**Comment by rtritto** [comment]
This issue is fixed in https://github.com/mongo-express/mongo-express/pull/1136 (related: https://github.com/mongo-express/mongo-express/issues/1162).
Current _Dockerfile_ build uses _mongo-express_ from npm package, so an update of npm version will fix this issue.

PS: maybe we should consider to build from _master_ branch of `mongo-express` (related: https://github.com/mongo-express/mongo-express-docker/pull/82#issuecomment-1249563687).

**Comment by rtritto** [comment]
> Building from master isn't ideal as far as Docker image go because there are no way to pin to a point in time.

You're right, we should use instead the branch of _version tag_.

**Comment by BlackthornYugen** [comment]
We worked around this last week by building from the release branch of mongo-express.
